services:
  server:
    image: augustine_will/server
    build: .
    ports: 
      - "7010:8080"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
    volumes:
      - type: bind
        source: ./dat
        target: /dat
    environment:
      DASH_URL_BASE_PATHNAME: "/augustine-graphtegner/"
